### ISSUE TITLE
removeAllListeners does not remove listeners added with onAny

### ISSUE THREAD

**Issue by nicholaswmin** [EventEmitter2/EventEmitter2#235]
Unless I'm missing something, I expect that `.removeAllListeners` removes all listeners added with `.onAny`.

```javascript
const ee = new EventEmitter2()
  
ee.onAny(() => console.log('hello was fired'))
setInterval(() => ee.emit('hello'), 500)

setTimeout(() => {
  ee.removeAllListeners()
  console.log('removed all listeners')
}, 1500)
```

Here's a "working" [JSFiddle](https://jsfiddle.net/g5u2o3r6/3/) of the above code.

The above example continues to listen to `hello` events indefinitely, even though `removeAllListeners` is called after 1500ms.

**Comment by RangerMauve** [comment]
Yeah, I think this is more of a documentation issue.

`onAny` acts as a special type of listener, and you need to use `offAny` in order to remove them.

If you want to remove _everything_ you need to invoke `ee.removeAllListeners()` __and__ `ee.offAny()`.

Chaning this would be pretty breaking to existing codebases so I'd rather not modify the behaviour unless it was preventing you from doing something.

A PR to modify the README to talk mention that `removeAllListeners` doesn't work for `onAny` listeners and that you should use `offAny` with no arguments would be very welcome!

**Comment by nicholaswmin** [comment]
@RangerMauve I'm guessing adding an additional method that combines those 2 together would make the API convoluted?

Perhaps, `offAll()`?

**Comment by RangerMauve** [comment]
Hmm, I'm not sure. One one hand it isn't strictly necessary, but it would be nice to have.

I think I'd rather wait for more input from other people before deciding. In the meantime, you could patch the prototype within your own projects if you want the feature.

```javascript
EventEmitter.prototype.offAll = function () {
  this.removeAllListeners();
  this.offAny()
};
```
