### ISSUE TITLE
'unsafe-eval' since 6.4.0

### ISSUE THREAD

**Issue by choppsta** [EventEmitter2/EventEmitter2#259]
https://github.com/EventEmitter2/EventEmitter2/blob/bca57698fcad30cefa99d7a9dbea541651faacc9/lib/eventemitter2.js#L306-L309

Since 6.4.0 this library relies on evaluating javascript at run time.  This is not supported in some enviroments that have a strict Content Security Policy.

For example, if used in a Chrome App it causes the following error:

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem: 'wasm-eval'".`

**Comment by DigitalBrainJS** [comment]
@choppsta Thanks for reporting! This will be fixed as soon as possible.

**Comment by choppsta** [comment]
Thank you Dmitriy.  Really appreciate you fixing this so quickly!

**Comment by DigitalBrainJS** [comment]
@choppsta you're welcome. I hope you use some js bundler instead of the module global script, since i realized we have another one eval there to export script to the global scope :D (https://github.com/EventEmitter2/EventEmitter2/blob/f76d81e682eaa09a60188bd170a44cb18afc747e/lib/eventemitter2.js#L1616)

**Comment by choppsta** [comment]
I'm using webpack, so not an issue for me!
