### ISSUE TITLE
Make it more ESM module friendly

### ISSUE THREAD

**Issue by miguelcobain** [EventEmitter2/EventEmitter2#281]
Right now, with ESM modules, we can't do this:
```js
import { EventEmitter2 } from 'eventemitter2';
```

and instead have to do this:
```js
import pkg from 'eventemitter2';
const { EventEmitter2 } = pkg;
```

This is a great blog post that explains the issue: https://simonplend.com/node-js-now-supports-named-imports-from-commonjs-modules-but-what-does-that-mean/

Is there anything we can do to make this library more friendly to modern module specs?
Ideally `EventEmitter2` would be a default export and not a named export.

**Comment by RangerMauve** [comment]
Is this using the ESM integration within Node.js or is this part of the functionality of a bundler like webpack?

**Comment by miguelcobain** [comment]
This is part of Node.js, yes, no bundler needed.

**Comment by RangerMauve** [comment]
I think EventEmitter2 initially got exported the way it has due to how Node.js' built-in `events` package worked. Would you be able to look into how that's been working in ESM and to see if we could do something similar here?

I'd be a bit worried about backwards compat, but maybe we could release a new major version for just those folks that want it. 🤷 Alternately, could we have a separate file for ESM imports that imports the commonjs module and then gives more appropriate ESM exports?

**Comment by danilofuchs** [comment]
This issue is not fixed.

Adding type definitions only tricks Typescript into thinking it works, when in reality the import breaks during runtime, as Node.js cannot find the EventEmitter2 named export.
